[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "vicibox"
authors = [{name = "James Pearson", email = "jamesp@vicidial.com"}]
dynamic = ["version", "description"]
